name: 'new-stock-calender-in-china-market'

on:
  schedule:
    - cron: '26,56 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout from repo
      uses: actions/checkout@main
      with:
        ref: main

    - name: Checkout private tools
      uses: actions/checkout@main
      with:
        repository: zning1994/new-stock-calender-scripts
        branch: main
        token: ${{ secrets.PRIVATE_TOEKEN }}
        path: scripts
    
    - name: Install Python latest
      uses: actions/setup-python@main
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
    - name: Doing fetch and convert
      run: |
        cd scripts;
        python Generate_New_Stocks.py;
        mv index.html ../;
        mv data ../;

    - name: Commit files
      run: |
        git config --local user.email "zhn038@gmail.com"
        git config --local user.name "ZNing"
        git add .
        git commit -m "提交新股日历更新 $(date "+%Y-%m-%d %H:%M:%S")"
 
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
